a = int(input("请输入需要计算的第一个数: "))
b = int(input("请输入需要计算的第二个数: "))
print("两数相加得：{0:f}".format(a+b))
print("两数相减得：{0:f}".format(a-b))
print("两数相乘得：{0:f}".format(a*b))
print("两数相除得：{0:f}".format(a/b))